config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'calculators#new'
  resources :calculators, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculator.rb
class Calculator < ApplicationRecord
  validates_presence_of :expression, :result
  
  def calculate
    @operators = self.expression.scan(/[\*\/\+\-]/)
    @operands = self.expression.split(/[\*\/\+\-]/)
    order_of_operations = ['*', '/', '+', '-']

    while @operands.length > 1
      order_of_operations.each do |operator|
        while @operators.include? operator
          operator_index = @operators.index(operator)
          evaluate(operator, operator_index)
        end
      end
    end
    self.result = @operands.first
  end

  def remove_elements(operator_index)
    @operands.delete_at(operator_index + 1)
    @operators.delete_at(operator_index)
  end

  def evaluate(operator, operator_index)
    case operator
      when '*'
        result = multiply(@operands[operator_index], @operands[operator_index + 1])
        @operands[operator_index] = result
        remove_elements(operator_index)
      when '/'
        result = divide(@operands[operator_index], @operands[operator_index + 1])
        @operands[operator_index] = result
        remove_elements(operator_index)
      when '+'
        result = add(@operands[operator_index], @operands[operator_index + 1])
        @operands[operator_index] = result
        remove_elements(operator_index)
      when '-'
        result = subtract(@operands[operator_index], @operands[operator_index + 1])
        @operands[operator_index] = result
        remove_elements(operator_index)
    end
  end

  def multiply(a, b)
    ('%.2f' % (a.to_f * b.to_f)).to_s
  end

  def divide(a, b)
    ('%.2f' % (a.to_f / b.to_f)).to_s
  end

  def add(a, b)
    ('%.2f' % (a.to_f + b.to_f)).to_s
  end

  def subtract(a, b)
    ('%.2f' % (a.to_f - b.to_f)).to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  def show
    @calculator = Calculator.find(params[:id])
  end
  
  def new
    @calculator = Calculator.new
  end
  
  def create
    @calculator = Calculator.new(calculator_params)
    @calculator.calculate

    if @calculator.save
      redirect_to @calculator
    else
      render 'new'
    end
  end

  def calculator_params
    params.require(:calculator).permit(:expression)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/views/calculators/new.html.erb
<h1>Calculate</h1>

<%= form_for(@calculator) do |f| %>
    <%= f.label :expression %>
    <%= f.text_field :expression %>
    <%= f.submit 'Calculate' %>
<% end %>

app/views/calculators/show.html.erb
<p>Expression: <%= @calculator.expression %></p>
<p>Result: <%= @calculator.result %></p>

<%= link_to 'Back', new_calculator_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalculatorApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>